### ISSUE TITLE
Cannot find SQLite.UWP.2015 and LinkAssemblies task failed unexpectedly errors

### ISSUE THREAD

**Issue by Netchicken** [Azure-Samples/MyDriving#542]
I am stuck on these errors. 
Anyone know what I should do?
Cheers

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find SDK "SQLite.UWP.2015, Version=3.12.1".	MyDriving.UWP	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	2049	

==========================================================

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item 'System.Threading.Tasks.Task`1<Acr.UserDialogs.PromptResult> Acr.UserDialogs.IUserDialogs::PromptAsync(Acr.UserDialogs.PromptConfig)' (defined in 'MyDriving, Version=1.0.6008.26923, Culture=neutral, PublicKeyToken=null') from 'MyDriving, Version=1.0.6008.26923, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task`1<Acr.UserDialogs.PromptResult> Acr.UserDialogs.IUserDialogs::PromptAsync(Acr.UserDialogs.PromptConfig)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   --- End of inner exception stack trace ---
   at Xamarin.Android.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MyDriving.Android	C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1616

**Comment by alinapopa** [comment]
For the first error (in UWP project), in Visual Studio, go to Tools ->Extensions and Updates
Install SQLite for Universal Windows Platform.
If the version is newer than 3.12.1, edit the MyDriving.UWP.csproj file and update this line with the right version
  `<SDKReference Include="SQLite.UWP.2015, Version=3.12.1">`

**Comment by Netchicken** [comment]
Thanks for that its running now with the changes
